// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-EMHJIPWQD-7wijhrImUDRkTTcGpZZk',
    appId: '1:780069058288:web:b25a06ffcc58ae3a2eb435',
    messagingSenderId: '780069058288',
    projectId: 'freshmart-24788',
    authDomain: 'freshmart-24788.firebaseapp.com',
    storageBucket: 'freshmart-24788.appspot.com',
    measurementId: 'G-B9R2L2MVNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvCckYBvoB3kHe5JaN5gxTAaVYtCY-Bvk',
    appId: '1:780069058288:android:92ef8550c689ec522eb435',
    messagingSenderId: '780069058288',
    projectId: 'freshmart-24788',
    storageBucket: 'freshmart-24788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARvTMd0jF9p4jFYIU4y7N8jM-nEFARYpw',
    appId: '1:780069058288:ios:1f7a22e4ba6c0a632eb435',
    messagingSenderId: '780069058288',
    projectId: 'freshmart-24788',
    storageBucket: 'freshmart-24788.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARvTMd0jF9p4jFYIU4y7N8jM-nEFARYpw',
    appId: '1:780069058288:ios:932ff5bf52c28cfd2eb435',
    messagingSenderId: '780069058288',
    projectId: 'freshmart-24788',
    storageBucket: 'freshmart-24788.appspot.com',
    iosBundleId: 'com.example.groceryApp.RunnerTests',
  );
}
